#!/usr/bin/env python3
"""Prepare MMDetection GroundingDINO-B D3 Route-A baseline files.

This repository's LaMI-DETR code path only has a complete ConvNeXt-L training
stack. Route A uses MMDetection's Swin-B GroundingDINO implementation as the
strong detector platform, so this helper writes the external MMDetection config
and a runnable eval shell script from local D3 paths.
"""

from __future__ import annotations

import argparse
import json
import stat
from pathlib import Path
from typing import Any, Dict


GROUNDINGDINO_B_CKPT = (
    "https://download.openmmlab.com/mmdetection/v3.0/grounding_dino/"
    "groundingdino_swinb_cogcoor_mmdet-55949c9c.pth"
)


def _jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {key: _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    return value


def _quote(value: str | Path) -> str:
    return repr(str(value))


def _count_categories(path: Path, default: int) -> int:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    categories = data.get("categories", [])
    return len(categories) if categories else default


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _make_config(args: argparse.Namespace, num_classes: int) -> str:
    base_config = Path(args.mmdet_root) / args.base_config
    lang_model_name = args.bert_path or "bert-base-uncased"

    return f"""# Auto-generated by LaMI-DETR tools/prepare_mmdet_groundingdino_d3.py.
# This config is intentionally eval-first: establish the Swin-B/GroundingDINO
# D3 baseline before adding description-conditioned query adaptation.

_base_ = {_quote(base_config)}

lang_model_name = {_quote(lang_model_name)}

model = dict(
    language_model=dict(name=lang_model_name),
    # GroundingDINO predicts over text-token positions, not dataset category ids.
    # Keep the OpenMMLab default text-token classification width; D3's 422
    # phrases are supplied through DODDataset text/positive maps.
    bbox_head=dict(num_classes={args.text_token_classes}),
    test_cfg=dict(max_per_img={args.max_per_img}),
)

dataset_type = 'DODDataset'
d3_ann_file = {_quote(args.d3_ann_file)}
d3_image_root = {_quote(args.d3_image_root)}
d3_pkl_root = {_quote(args.d3_pkl_root)}

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None, imdecode_backend='pillow'),
    dict(type='FixScaleResize', scale=({args.test_short_edge}, {args.test_long_edge}), keep_ratio=True, backend='pillow'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'text',
            'custom_entities',
            'tokens_positive',
        ),
    ),
]

test_dataloader = dict(
    batch_size={args.batch_size},
    num_workers={args.num_workers},
    persistent_workers=False,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root='',
        ann_file=d3_ann_file,
        data_prefix=dict(img=d3_image_root, anno=d3_pkl_root),
        test_mode=True,
        pipeline=test_pipeline,
        return_classes=True,
    ),
)
val_dataloader = test_dataloader

test_evaluator = dict(
    type='CocoMetric',
    ann_file=d3_ann_file,
    metric='bbox',
    format_only=False,
)
val_evaluator = test_evaluator

train_cfg = None
train_dataloader = None
optim_wrapper = None
param_scheduler = None
"""


def _make_run_script(args: argparse.Namespace, config_path: Path) -> str:
    checkpoint = args.checkpoint
    return f"""#!/usr/bin/env bash
set -euo pipefail

MMDET_DIR={_quote(args.mmdet_root)}
CONFIG={_quote(config_path)}
CHECKPOINT={_quote(checkpoint)}
WORK_DIR={_quote(args.work_dir)}

cd "$MMDET_DIR"
mkdir -p "$WORK_DIR"

python tools/test.py "$CONFIG" "$CHECKPOINT" --work-dir "$WORK_DIR"
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mmdet-root",
        type=Path,
        required=True,
        help="MMDetection checkout root, e.g. /root/autodl-tmp/mmdetection.",
    )
    parser.add_argument(
        "--d3-ann-file",
        type=Path,
        required=True,
        help="D3 COCO-style annotation JSON for the split to evaluate.",
    )
    parser.add_argument(
        "--d3-image-root",
        type=Path,
        required=True,
        help="D3 image directory passed to ddd-dataset/DODDataset.",
    )
    parser.add_argument(
        "--d3-pkl-root",
        type=Path,
        required=True,
        help="D3 pkl annotation root/file required by ddd-dataset.",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=Path("work_dirs/lami_route_a_gdino_b_d3"),
        help="Work dir used by generated MMDetection run script.",
    )
    parser.add_argument(
        "--checkpoint",
        default=GROUNDINGDINO_B_CKPT,
        help="GroundingDINO-B checkpoint path or URL.",
    )
    parser.add_argument(
        "--base-config",
        default="configs/grounding_dino/grounding_dino_swin-b_pretrain_mixeddata.py",
        help="Path under --mmdet-root for the MMDetection base config.",
    )
    parser.add_argument(
        "--bert-path",
        default=None,
        help="Optional local bert-base-uncased path for offline AutoDL runs.",
    )
    parser.add_argument("--num-classes", type=int, default=422)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--max-per-img", type=int, default=300)
    parser.add_argument(
        "--text-token-classes",
        type=int,
        default=256,
        help="GroundingDINO head text-token classification width; do not set this to D3 category count.",
    )
    parser.add_argument("--test-short-edge", type=int, default=800)
    parser.add_argument("--test-long-edge", type=int, default=1333)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    num_classes = _count_categories(args.d3_ann_file, args.num_classes)

    config_path = args.output_dir / "grounding_dino_swin-b_d3_dod_eval.py"
    run_path = args.output_dir / "run_eval.sh"
    manifest_path = args.output_dir / "manifest.json"

    _write_text(config_path, _make_config(args, num_classes))
    _write_text(run_path, _make_run_script(args, config_path.resolve()))
    run_path.chmod(run_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    manifest: Dict[str, Any] = {
        "purpose": "Route A baseline: MMDetection GroundingDINO-B/Swin-B on D3",
        "config": str(config_path.resolve()),
        "run_script": str(run_path.resolve()),
        "num_classes": num_classes,
        "args": {key: _jsonable(value) for key, value in vars(args).items()},
        "expected_reference": {
            "source": "OpenMMLab GroundingDINO README DOD table",
            "grounding_dino_b_full_concat": 20.2,
            "grounding_dino_b_full_parallel": 25.0,
        },
    }
    _write_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True))
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
