#!/usr/bin/env python3
"""Prepare MMDetection GroundingDINO-B D3 Route-A baseline files.

This repository's LaMI-DETR code path only has a complete ConvNeXt-L training
stack. Route A uses MMDetection's Swin-B GroundingDINO implementation as the
strong detector platform, so this helper writes the external MMDetection config
and a runnable eval shell script from local D3 paths.
"""

from __future__ import annotations

import argparse
import json
import stat
from pathlib import Path
from typing import Any, Dict


GROUNDINGDINO_B_CKPT = (
    "https://download.openmmlab.com/mmdetection/v3.0/grounding_dino/"
    "groundingdino_swinb_cogcoor_mmdet-55949c9c.pth"
)

DEFAULT_TRAINABLE_PREFIXES = (
    "text_query_adapter",
    "dn_query_generator.label_embedding",
)


def _jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {key: _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    return value


def _quote(value: str | Path) -> str:
    return repr(str(value))


def _count_categories(path: Path, default: int) -> int:
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    categories = data.get("categories", [])
    return len(categories) if categories else default


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _make_test_cfg(args: argparse.Namespace) -> str:
    items = [f"max_per_img={args.max_per_img}"]
    if args.inference_mode == "parallel":
        items.append(f"chunked_size={args.chunked_size}")
    return f"dict({', '.join(items)})"


def _make_model_train_cfg() -> str:
    return """dict(
        _delete_=True,
        assigner=dict(
            type='HungarianAssigner',
            match_costs=[
                dict(type='BinaryFocalLossCost', weight=2.0),
                dict(type='BBoxL1Cost', weight=5.0, box_format='xywh'),
                dict(type='IoUCost', iou_mode='giou', weight=2.0),
            ],
        )
    )"""


def _make_bbox_head_cfg(args: argparse.Namespace, is_train: bool) -> str:
    items = [f"num_classes={args.text_token_classes}"]
    if is_train:
        items.append("loss_iou=dict(type='GIoULoss', loss_weight=2.0)")
    return f"dict({', '.join(items)})"


def _quote_tuple(values: tuple[str, ...]) -> str:
    return "(" + ", ".join(_quote(value) for value in values) + ("," if len(values) == 1 else "") + ")"


def _make_config(args: argparse.Namespace, num_classes: int) -> str:
    base_config = Path(args.mmdet_root) / args.base_config
    lang_model_name = args.bert_path or "bert-base-uncased"
    test_cfg = _make_test_cfg(args)
    is_train = args.train_ann_file is not None
    bbox_head_cfg = _make_bbox_head_cfg(args, is_train)
    model_train_cfg = _make_model_train_cfg() if is_train else "None"
    use_plugin_dataset = is_train or args.use_subset_dataset
    val_ann_file = args.val_ann_file or args.d3_ann_file
    eval_ann_ref = "d3_val_ann_file" if is_train else "d3_ann_file"
    dataset_type = "D3SubsetDODDataset" if use_plugin_dataset else "DODDataset"
    custom_imports = (
        "custom_imports = dict(imports=['tools.mmdet_d3_route_a'], allow_failed_imports=False)\n\n"
        if use_plugin_dataset
        else ""
    )
    model_type = (
        "    type='GroundingDINOTextQueryAdapter',\n"
        f"    text_query_adapter=dict(bottleneck_dim={args.adapter_bottleneck_dim}, "
        f"dropout={args.adapter_dropout}, init_scale={args.adapter_init_scale}),\n"
        if is_train
        else ""
    )
    load_from = f"load_from = {_quote(args.checkpoint)}\n" if is_train else ""
    trainable_prefixes = tuple(args.trainable_prefix or DEFAULT_TRAINABLE_PREFIXES)

    return f"""# Auto-generated by LaMI-DETR tools/prepare_mmdet_groundingdino_d3.py.
# This config is intentionally eval-first: establish the Swin-B/GroundingDINO
# D3 baseline before adding description-conditioned query adaptation.

_base_ = {_quote(base_config)}

{custom_imports}\
lang_model_name = {_quote(lang_model_name)}
{load_from}

model = dict(
{model_type}\
    language_model=dict(name=lang_model_name),
    # GroundingDINO predicts over text-token positions, not dataset category ids.
    # Keep the OpenMMLab default text-token classification width; D3's 422
    # phrases are supplied through DODDataset text/positive maps.
    bbox_head={bbox_head_cfg},
    train_cfg={model_train_cfg},
    test_cfg={test_cfg},
)

dataset_type = {_quote(dataset_type)}
d3_ann_file = {_quote(args.d3_ann_file)}
d3_train_ann_file = {_quote(args.train_ann_file or args.d3_ann_file)}
d3_val_ann_file = {_quote(val_ann_file)}
d3_image_root = {_quote(args.d3_image_root)}
d3_pkl_root = {_quote(args.d3_pkl_root)}

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None, imdecode_backend='pillow'),
    dict(type='FixScaleResize', scale=({args.test_short_edge}, {args.test_long_edge}), keep_ratio=True, backend='pillow'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'text',
            'custom_entities',
            'tokens_positive',
            'sent_ids',
        ),
    ),
]

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None, imdecode_backend='pillow'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='FixScaleResize', scale=({args.test_short_edge}, {args.test_long_edge}), keep_ratio=True, backend='pillow'),
    dict(
        type='PackDetInputs',
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'text',
            'custom_entities',
            'tokens_positive',
            'sent_ids',
        ),
    ),
]

test_dataloader = dict(
    _delete_=True,
    batch_size={args.batch_size},
    num_workers={args.num_workers},
    persistent_workers=False,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root='',
        ann_file={'d3_val_ann_file' if is_train else 'd3_ann_file'},
        data_prefix=dict(img=d3_image_root, anno=d3_pkl_root),
        test_mode=True,
        pipeline=test_pipeline,
        return_classes=True,
    ),
)
val_dataloader = test_dataloader

train_dataloader = {'''dict(
    _delete_=True,
    batch_size=''' + str(args.batch_size) + ''',
    num_workers=''' + str(args.num_workers) + ''',
    persistent_workers=False,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root='',
        ann_file=d3_train_ann_file,
        data_prefix=dict(img=d3_image_root, anno=d3_pkl_root),
        test_mode=False,
        pipeline=train_pipeline,
        return_classes=True,
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
    ),
)''' if is_train else 'None'}

test_evaluator = dict(
    _delete_=True,
    # DODDataset returns image-local phrase labels at prediction time. The DOD
    # metric maps those local labels back to global D3 sent_ids before COCO eval.
    # Plain CocoMetric will silently evaluate the wrong category ids and can
    # produce near-zero AP even when boxes are reasonable.
    type='DODCocoMetric',
    ann_file={eval_ann_ref},
)
val_evaluator = test_evaluator

train_cfg = {f"dict(_delete_=True, type='IterBasedTrainLoop', max_iters={args.max_iter}, val_interval={args.val_interval})" if is_train else 'None'}
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

optim_wrapper = {'''dict(
    _delete_=True,
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=''' + str(args.train_lr) + ''', weight_decay=''' + str(args.weight_decay) + '''),
    clip_grad=dict(max_norm=0.1, norm_type=2),
)''' if is_train else 'None'}
param_scheduler = {'[]' if is_train else 'None'}

custom_hooks = {'''[
    dict(
        type='TrainableParamFreezeHook',
        trainable_prefixes=''' + _quote_tuple(trainable_prefixes) + ''',
    )
]''' if is_train else '[]'}

default_hooks = dict(
    checkpoint=dict(type='CheckpointHook', by_epoch=False, interval={args.checkpoint_interval}, max_keep_ckpts=3),
    logger=dict(type='LoggerHook', interval={args.log_interval}),
)
log_processor = dict(type='LogProcessor', window_size=50, by_epoch=False)
"""


def _make_run_script(args: argparse.Namespace, config_path: Path) -> str:
    checkpoint = args.checkpoint
    repo_root = Path(args.repo_root).resolve()
    if args.train_ann_file is not None:
        command = 'python tools/train.py "$CONFIG" --work-dir "$WORK_DIR"'
    else:
        command = 'python tools/test.py "$CONFIG" "$CHECKPOINT" --work-dir "$WORK_DIR"'
    return f"""#!/usr/bin/env bash
set -euo pipefail

MMDET_DIR={_quote(args.mmdet_root)}
CONFIG={_quote(config_path)}
CHECKPOINT={_quote(checkpoint)}
WORK_DIR={_quote(args.work_dir)}
REPO_ROOT={_quote(repo_root)}

cd "$MMDET_DIR"
mkdir -p "$WORK_DIR"
export PYTHONPATH="$REPO_ROOT:${{PYTHONPATH:-}}"

{command}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mmdet-root",
        type=Path,
        required=True,
        help="MMDetection checkout root, e.g. /root/autodl-tmp/mmdetection.",
    )
    parser.add_argument(
        "--d3-ann-file",
        type=Path,
        required=True,
        help="D3 COCO-style annotation JSON for the split to evaluate.",
    )
    parser.add_argument(
        "--d3-image-root",
        type=Path,
        required=True,
        help="D3 image directory passed to ddd-dataset/DODDataset.",
    )
    parser.add_argument(
        "--d3-pkl-root",
        type=Path,
        required=True,
        help="D3 pkl annotation root/file required by ddd-dataset.",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=Path("work_dirs/lami_route_a_gdino_b_d3"),
        help="Work dir used by generated MMDetection run script.",
    )
    parser.add_argument(
        "--checkpoint",
        default=GROUNDINGDINO_B_CKPT,
        help="GroundingDINO-B checkpoint path or URL.",
    )
    parser.add_argument(
        "--base-config",
        default="configs/grounding_dino/grounding_dino_swin-b_pretrain_mixeddata.py",
        help="Path under --mmdet-root for the MMDetection base config.",
    )
    parser.add_argument(
        "--bert-path",
        default=None,
        help="Optional local bert-base-uncased path for offline AutoDL runs.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="LaMI-DETR/ovd-poc repository root to add to PYTHONPATH for Route-A plugins.",
    )
    parser.add_argument(
        "--train-ann-file",
        type=Path,
        default=None,
        help="Optional D3 train split COCO JSON. Supplying this generates an adapter training config.",
    )
    parser.add_argument(
        "--val-ann-file",
        type=Path,
        default=None,
        help="Optional D3 validation split COCO JSON for adapter training.",
    )
    parser.add_argument(
        "--use-subset-dataset",
        action="store_true",
        help="Filter D3 image ids by --d3-ann-file for strict-split eval configs.",
    )
    parser.add_argument("--num-classes", type=int, default=422)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--max-per-img", type=int, default=300)
    parser.add_argument(
        "--inference-mode",
        choices=("concat", "parallel"),
        default="concat",
        help=(
            "D3/DOD inference mode. concat uses the default prompt concatenation; "
            "parallel sets GroundingDINO test_cfg.chunked_size so sub-sentences "
            "are evaluated in a loop."
        ),
    )
    parser.add_argument(
        "--chunked-size",
        type=int,
        default=1,
        help="Text chunk size used when --inference-mode=parallel. Use 1 to reproduce the official D3 parallel baseline.",
    )
    parser.add_argument(
        "--text-token-classes",
        type=int,
        default=256,
        help="GroundingDINO head text-token classification width; do not set this to D3 category count.",
    )
    parser.add_argument("--max-iter", type=int, default=1000)
    parser.add_argument("--val-interval", type=int, default=500)
    parser.add_argument("--checkpoint-interval", type=int, default=500)
    parser.add_argument("--log-interval", type=int, default=50)
    parser.add_argument("--train-lr", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=0.05)
    parser.add_argument("--adapter-bottleneck-dim", type=int, default=64)
    parser.add_argument("--adapter-dropout", type=float, default=0.0)
    parser.add_argument("--adapter-init-scale", type=float, default=1.0)
    parser.add_argument(
        "--trainable-prefix",
        action="append",
        default=None,
        help=(
            "Parameter prefix to leave trainable in adapter training. Can be repeated. "
            "Defaults to text_query_adapter and dn_query_generator.label_embedding."
        ),
    )
    parser.add_argument("--test-short-edge", type=int, default=800)
    parser.add_argument("--test-long-edge", type=int, default=1333)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    num_classes = _count_categories(args.d3_ann_file, args.num_classes)
    is_train = args.train_ann_file is not None

    config_name = "grounding_dino_swin-b_d3_dod_adapter_train.py" if is_train else "grounding_dino_swin-b_d3_dod_eval.py"
    run_name = "run_train.sh" if is_train else "run_eval.sh"
    config_path = args.output_dir / config_name
    run_path = args.output_dir / run_name
    manifest_path = args.output_dir / "manifest.json"

    _write_text(config_path, _make_config(args, num_classes))
    _write_text(run_path, _make_run_script(args, config_path.resolve()))
    run_path.chmod(run_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    manifest: Dict[str, Any] = {
        "purpose": (
            "Route A adapter training: MMDetection GroundingDINO-B/Swin-B on D3"
            if is_train
            else "Route A baseline: MMDetection GroundingDINO-B/Swin-B on D3"
        ),
        "config": str(config_path.resolve()),
        "run_script": str(run_path.resolve()),
        "num_classes": num_classes,
        "inference_mode": args.inference_mode,
        "train_mode": is_train,
        "args": {key: _jsonable(value) for key, value in vars(args).items()},
        "expected_reference": {
            "source": "OpenMMLab GroundingDINO README DOD table",
            "grounding_dino_b_full_concat": 20.2,
            "grounding_dino_b_full_parallel": 25.0,
        },
    }
    _write_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True))
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
